version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[MNT] [Dependabot]"
      include: "scope"
    labels:
      - "maintenance"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[MNT] [Dependabot]"
      include: "scope"
    labels:
      - "maintenance"
  - package-ecosystem: "docker"
    directories:
      - "/Docker_files/pycaret_slim"
      - "/Docker_files/pycaret_full"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[MNT] [Dependabot]"
      include: "scope"
    labels:
      - "maintenance"
